// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  weddingId: __t.u64().name("wedding_id"),
  kind: __t.string(),
  targetIdentity: __t.identity().name("target_identity"),
  instruction: __t.string(),
  scheduledFor: __t.option(__t.timestamp()).name("scheduled_for"),
  status: __t.string(),
  state: __t.string(),
  source: __t.string(),
  requestedBy: __t.identity().name("requested_by"),
  requestedAt: __t.timestamp().name("requested_at"),
  updatedBy: __t.identity().name("updated_by"),
  confidence: __t.f32(),
  updatedAt: __t.timestamp().name("updated_at"),
  taskId: __t.option(__t.u64()).name("task_id"),
});
