// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptWeddingInvitationReducer from "./accept_wedding_invitation_reducer";
import AddEventChecklistItemReducer from "./add_event_checklist_item_reducer";
import AddMemberReducer from "./add_member_reducer";
import ApplyEventTemplateReducer from "./apply_event_template_reducer";
import CastVoteReducer from "./cast_vote_reducer";
import ConfirmEventChecklistItemReducer from "./confirm_event_checklist_item_reducer";
import ConfirmExpenseReducer from "./confirm_expense_reducer";
import ConfirmReportedTaskReducer from "./confirm_reported_task_reducer";
import CreateCustomWeddingAgentReducer from "./create_custom_wedding_agent_reducer";
import CreateDecisionReducer from "./create_decision_reducer";
import CreateEventReducer from "./create_event_reducer";
import CreateExpenseReducer from "./create_expense_reducer";
import CreateTaskReducer from "./create_task_reducer";
import CreateVendorReducer from "./create_vendor_reducer";
import CreateWeddingReducer from "./create_wedding_reducer";
import CreateWeddingInvitationReducer from "./create_wedding_invitation_reducer";
import LinkPhoneReducer from "./link_phone_reducer";
import LockDecisionReducer from "./lock_decision_reducer";
import RecordImportedExpenseReducer from "./record_imported_expense_reducer";
import RequestCoordinatorActionReducer from "./request_coordinator_action_reducer";
import RequestIngestReducer from "./request_ingest_reducer";
import SeedPriyaRahulDemoReducer from "./seed_priya_rahul_demo_reducer";
import SendWeddingMessageReducer from "./send_wedding_message_reducer";
import SetBudgetReducer from "./set_budget_reducer";
import SetDeciderReducer from "./set_decider_reducer";
import SetEventChecklistItemDoneReducer from "./set_event_checklist_item_done_reducer";
import SetMembershipRoleReducer from "./set_membership_role_reducer";
import SetMembershipSideReducer from "./set_membership_side_reducer";
import SetNameReducer from "./set_name_reducer";
import SetRoleReducer from "./set_role_reducer";
import SetSideReducer from "./set_side_reducer";
import SetVendorBookingStateReducer from "./set_vendor_booking_state_reducer";
import SetVendorConsentReducer from "./set_vendor_consent_reducer";
import SetWebhookSecretReducer from "./set_webhook_secret_reducer";
import SetWeddingAgentReducer from "./set_wedding_agent_reducer";
import SetWeddingAgentInstructionsReducer from "./set_wedding_agent_instructions_reducer";
import ToggleTaskReducer from "./toggle_task_reducer";
import UpdateMyProfileReducer from "./update_my_profile_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import BudgetRow from "./budget_table";
import CoordinatorRequestRow from "./coordinator_request_table";
import CustomWeddingAgentRow from "./custom_wedding_agent_table";
import DecisionRow from "./decision_table";
import DecisionOptionRow from "./decision_option_table";
import EventRow from "./event_table";
import EventChecklistItemRow from "./event_checklist_item_table";
import ExpenseRow from "./expense_table";
import GuestRow from "./guest_table";
import IngestSourceRow from "./ingest_source_table";
import MemberRow from "./member_table";
import MoodItemRow from "./mood_item_table";
import ParticipantRow from "./participant_table";
import TaskRow from "./task_table";
import VendorRow from "./vendor_table";
import VendorConsentRow from "./vendor_consent_table";
import VoteRow from "./vote_table";
import WeddingRow from "./wedding_table";
import WeddingAgentRow from "./wedding_agent_table";
import WeddingAgentSettingRow from "./wedding_agent_setting_table";
import WeddingMessageRow from "./wedding_message_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  budget: __table({
    name: 'budget',
    indexes: [
      { accessor: 'id', name: 'budget_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding', name: 'budget_wedding_id_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
      ] },
    ],
    constraints: [
      { name: 'budget_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BudgetRow),
  coordinatorRequest: __table({
    name: 'coordinator_request',
    indexes: [
      { accessor: 'id', name: 'coordinator_request_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding_status', name: 'coordinator_request_wedding_id_status_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
        'status',
      ] },
    ],
    constraints: [
      { name: 'coordinator_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CoordinatorRequestRow),
  customWeddingAgent: __table({
    name: 'custom_wedding_agent',
    indexes: [
      { accessor: 'id', name: 'custom_wedding_agent_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding', name: 'custom_wedding_agent_wedding_id_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
      ] },
    ],
    constraints: [
      { name: 'custom_wedding_agent_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CustomWeddingAgentRow),
  decision: __table({
    name: 'decision',
    indexes: [
      { accessor: 'id', name: 'decision_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'decision_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DecisionRow),
  decisionOption: __table({
    name: 'decision_option',
    indexes: [
      { accessor: 'id', name: 'decision_option_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'decision_option_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DecisionOptionRow),
  event: __table({
    name: 'event',
    indexes: [
      { accessor: 'id', name: 'event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding', name: 'event_wedding_id_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
      ] },
    ],
    constraints: [
      { name: 'event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventRow),
  eventChecklistItem: __table({
    name: 'event_checklist_item',
    indexes: [
      { accessor: 'by_event', name: 'event_checklist_item_event_id_idx_btree', algorithm: 'btree', columns: [
        'eventId',
      ] },
      { accessor: 'id', name: 'event_checklist_item_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding', name: 'event_checklist_item_wedding_id_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
      ] },
    ],
    constraints: [
      { name: 'event_checklist_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventChecklistItemRow),
  expense: __table({
    name: 'expense',
    indexes: [
      { accessor: 'id', name: 'expense_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding', name: 'expense_wedding_id_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
      ] },
    ],
    constraints: [
      { name: 'expense_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ExpenseRow),
  guest: __table({
    name: 'guest',
    indexes: [
      { accessor: 'id', name: 'guest_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding', name: 'guest_wedding_id_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
      ] },
    ],
    constraints: [
      { name: 'guest_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GuestRow),
  ingestSource: __table({
    name: 'ingest_source',
    indexes: [
      { accessor: 'id', name: 'ingest_source_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding', name: 'ingest_source_wedding_id_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
      ] },
    ],
    constraints: [
      { name: 'ingest_source_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, IngestSourceRow),
  member: __table({
    name: 'member',
    indexes: [
      { accessor: 'id', name: 'member_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_identity', name: 'member_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'by_wedding_identity', name: 'member_wedding_id_identity_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
        'identity',
      ] },
    ],
    constraints: [
      { name: 'member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MemberRow),
  moodItem: __table({
    name: 'mood_item',
    indexes: [
      { accessor: 'id', name: 'mood_item_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding', name: 'mood_item_wedding_id_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
      ] },
    ],
    constraints: [
      { name: 'mood_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MoodItemRow),
  participant: __table({
    name: 'participant',
    indexes: [
      { accessor: 'identity', name: 'participant_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'by_phone', name: 'participant_phone_idx_btree', algorithm: 'btree', columns: [
        'phone',
      ] },
    ],
    constraints: [
      { name: 'participant_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, ParticipantRow),
  task: __table({
    name: 'task',
    indexes: [
      { accessor: 'id', name: 'task_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'task_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TaskRow),
  vendor: __table({
    name: 'vendor',
    indexes: [
      { accessor: 'id', name: 'vendor_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding', name: 'vendor_wedding_id_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
      ] },
    ],
    constraints: [
      { name: 'vendor_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VendorRow),
  vendorConsent: __table({
    name: 'vendor_consent',
    indexes: [
      { accessor: 'id', name: 'vendor_consent_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_vendor', name: 'vendor_consent_vendor_id_idx_btree', algorithm: 'btree', columns: [
        'vendorId',
      ] },
    ],
    constraints: [
      { name: 'vendor_consent_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VendorConsentRow),
  vote: __table({
    name: 'vote',
    indexes: [
      { accessor: 'by_decision_voter', name: 'vote_decision_id_voter_identity_idx_btree', algorithm: 'btree', columns: [
        'decisionId',
        'voterIdentity',
      ] },
      { accessor: 'id', name: 'vote_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'vote_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VoteRow),
  wedding: __table({
    name: 'wedding',
    indexes: [
      { accessor: 'id', name: 'wedding_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'wedding_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WeddingRow),
  weddingAgent: __table({
    name: 'wedding_agent',
    indexes: [
      { accessor: 'id', name: 'wedding_agent_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding_kind', name: 'wedding_agent_wedding_id_kind_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
        'kind',
      ] },
    ],
    constraints: [
      { name: 'wedding_agent_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WeddingAgentRow),
  weddingAgentSetting: __table({
    name: 'wedding_agent_setting',
    indexes: [
      { accessor: 'id', name: 'wedding_agent_setting_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding_kind', name: 'wedding_agent_setting_wedding_id_kind_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
        'kind',
      ] },
    ],
    constraints: [
      { name: 'wedding_agent_setting_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WeddingAgentSettingRow),
  weddingMessage: __table({
    name: 'wedding_message',
    indexes: [
      { accessor: 'id', name: 'wedding_message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_wedding', name: 'wedding_message_wedding_id_idx_btree', algorithm: 'btree', columns: [
        'weddingId',
      ] },
    ],
    constraints: [
      { name: 'wedding_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WeddingMessageRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_wedding_invitation", AcceptWeddingInvitationReducer),
  __reducerSchema("add_event_checklist_item", AddEventChecklistItemReducer),
  __reducerSchema("add_member", AddMemberReducer),
  __reducerSchema("apply_event_template", ApplyEventTemplateReducer),
  __reducerSchema("cast_vote", CastVoteReducer),
  __reducerSchema("confirm_event_checklist_item", ConfirmEventChecklistItemReducer),
  __reducerSchema("confirm_expense", ConfirmExpenseReducer),
  __reducerSchema("confirm_reported_task", ConfirmReportedTaskReducer),
  __reducerSchema("create_custom_wedding_agent", CreateCustomWeddingAgentReducer),
  __reducerSchema("create_decision", CreateDecisionReducer),
  __reducerSchema("create_event", CreateEventReducer),
  __reducerSchema("create_expense", CreateExpenseReducer),
  __reducerSchema("create_task", CreateTaskReducer),
  __reducerSchema("create_vendor", CreateVendorReducer),
  __reducerSchema("create_wedding", CreateWeddingReducer),
  __reducerSchema("create_wedding_invitation", CreateWeddingInvitationReducer),
  __reducerSchema("link_phone", LinkPhoneReducer),
  __reducerSchema("lock_decision", LockDecisionReducer),
  __reducerSchema("record_imported_expense", RecordImportedExpenseReducer),
  __reducerSchema("request_coordinator_action", RequestCoordinatorActionReducer),
  __reducerSchema("request_ingest", RequestIngestReducer),
  __reducerSchema("seed_priya_rahul_demo", SeedPriyaRahulDemoReducer),
  __reducerSchema("send_wedding_message", SendWeddingMessageReducer),
  __reducerSchema("set_budget", SetBudgetReducer),
  __reducerSchema("set_decider", SetDeciderReducer),
  __reducerSchema("set_event_checklist_item_done", SetEventChecklistItemDoneReducer),
  __reducerSchema("set_membership_role", SetMembershipRoleReducer),
  __reducerSchema("set_membership_side", SetMembershipSideReducer),
  __reducerSchema("set_name", SetNameReducer),
  __reducerSchema("set_role", SetRoleReducer),
  __reducerSchema("set_side", SetSideReducer),
  __reducerSchema("set_vendor_booking_state", SetVendorBookingStateReducer),
  __reducerSchema("set_vendor_consent", SetVendorConsentReducer),
  __reducerSchema("set_webhook_secret", SetWebhookSecretReducer),
  __reducerSchema("set_wedding_agent", SetWeddingAgentReducer),
  __reducerSchema("set_wedding_agent_instructions", SetWeddingAgentInstructionsReducer),
  __reducerSchema("toggle_task", ToggleTaskReducer),
  __reducerSchema("update_my_profile", UpdateMyProfileReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `coordinatorRequest` instead. This alias will be removed in the next major version. */
    readonly "coordinator_request": Omit<typeof tablesSchema.schemaType.tables["coordinatorRequest"], "accessorName"> & { readonly accessorName: "coordinator_request" };
    /** @deprecated Use `customWeddingAgent` instead. This alias will be removed in the next major version. */
    readonly "custom_wedding_agent": Omit<typeof tablesSchema.schemaType.tables["customWeddingAgent"], "accessorName"> & { readonly accessorName: "custom_wedding_agent" };
    /** @deprecated Use `decisionOption` instead. This alias will be removed in the next major version. */
    readonly "decision_option": Omit<typeof tablesSchema.schemaType.tables["decisionOption"], "accessorName"> & { readonly accessorName: "decision_option" };
    /** @deprecated Use `eventChecklistItem` instead. This alias will be removed in the next major version. */
    readonly "event_checklist_item": Omit<typeof tablesSchema.schemaType.tables["eventChecklistItem"], "accessorName"> & { readonly accessorName: "event_checklist_item" };
    /** @deprecated Use `ingestSource` instead. This alias will be removed in the next major version. */
    readonly "ingest_source": Omit<typeof tablesSchema.schemaType.tables["ingestSource"], "accessorName"> & { readonly accessorName: "ingest_source" };
    /** @deprecated Use `moodItem` instead. This alias will be removed in the next major version. */
    readonly "mood_item": Omit<typeof tablesSchema.schemaType.tables["moodItem"], "accessorName"> & { readonly accessorName: "mood_item" };
    /** @deprecated Use `vendorConsent` instead. This alias will be removed in the next major version. */
    readonly "vendor_consent": Omit<typeof tablesSchema.schemaType.tables["vendorConsent"], "accessorName"> & { readonly accessorName: "vendor_consent" };
    /** @deprecated Use `weddingAgent` instead. This alias will be removed in the next major version. */
    readonly "wedding_agent": Omit<typeof tablesSchema.schemaType.tables["weddingAgent"], "accessorName"> & { readonly accessorName: "wedding_agent" };
    /** @deprecated Use `weddingAgentSetting` instead. This alias will be removed in the next major version. */
    readonly "wedding_agent_setting": Omit<typeof tablesSchema.schemaType.tables["weddingAgentSetting"], "accessorName"> & { readonly accessorName: "wedding_agent_setting" };
    /** @deprecated Use `weddingMessage` instead. This alias will be removed in the next major version. */
    readonly "wedding_message": Omit<typeof tablesSchema.schemaType.tables["weddingMessage"], "accessorName"> & { readonly accessorName: "wedding_message" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "coordinator_request": "coordinatorRequest",
  "custom_wedding_agent": "customWeddingAgent",
  "decision_option": "decisionOption",
  "event_checklist_item": "eventChecklistItem",
  "ingest_source": "ingestSource",
  "mood_item": "moodItem",
  "vendor_consent": "vendorConsent",
  "wedding_agent": "weddingAgent",
  "wedding_agent_setting": "weddingAgentSetting",
  "wedding_message": "weddingMessage",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `coordinatorRequest` instead. This alias will be removed in the next major version. */
  readonly "coordinator_request": __DbViewBase["coordinatorRequest"];
  /** @deprecated Use `customWeddingAgent` instead. This alias will be removed in the next major version. */
  readonly "custom_wedding_agent": __DbViewBase["customWeddingAgent"];
  /** @deprecated Use `decisionOption` instead. This alias will be removed in the next major version. */
  readonly "decision_option": __DbViewBase["decisionOption"];
  /** @deprecated Use `eventChecklistItem` instead. This alias will be removed in the next major version. */
  readonly "event_checklist_item": __DbViewBase["eventChecklistItem"];
  /** @deprecated Use `ingestSource` instead. This alias will be removed in the next major version. */
  readonly "ingest_source": __DbViewBase["ingestSource"];
  /** @deprecated Use `moodItem` instead. This alias will be removed in the next major version. */
  readonly "mood_item": __DbViewBase["moodItem"];
  /** @deprecated Use `vendorConsent` instead. This alias will be removed in the next major version. */
  readonly "vendor_consent": __DbViewBase["vendorConsent"];
  /** @deprecated Use `weddingAgent` instead. This alias will be removed in the next major version. */
  readonly "wedding_agent": __DbViewBase["weddingAgent"];
  /** @deprecated Use `weddingAgentSetting` instead. This alias will be removed in the next major version. */
  readonly "wedding_agent_setting": __DbViewBase["weddingAgentSetting"];
  /** @deprecated Use `weddingMessage` instead. This alias will be removed in the next major version. */
  readonly "wedding_message": __DbViewBase["weddingMessage"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `coordinatorRequest` instead. This alias will be removed in the next major version. */
  readonly "coordinator_request": __TablesBase["coordinatorRequest"];
  /** @deprecated Use `customWeddingAgent` instead. This alias will be removed in the next major version. */
  readonly "custom_wedding_agent": __TablesBase["customWeddingAgent"];
  /** @deprecated Use `decisionOption` instead. This alias will be removed in the next major version. */
  readonly "decision_option": __TablesBase["decisionOption"];
  /** @deprecated Use `eventChecklistItem` instead. This alias will be removed in the next major version. */
  readonly "event_checklist_item": __TablesBase["eventChecklistItem"];
  /** @deprecated Use `ingestSource` instead. This alias will be removed in the next major version. */
  readonly "ingest_source": __TablesBase["ingestSource"];
  /** @deprecated Use `moodItem` instead. This alias will be removed in the next major version. */
  readonly "mood_item": __TablesBase["moodItem"];
  /** @deprecated Use `vendorConsent` instead. This alias will be removed in the next major version. */
  readonly "vendor_consent": __TablesBase["vendorConsent"];
  /** @deprecated Use `weddingAgent` instead. This alias will be removed in the next major version. */
  readonly "wedding_agent": __TablesBase["weddingAgent"];
  /** @deprecated Use `weddingAgentSetting` instead. This alias will be removed in the next major version. */
  readonly "wedding_agent_setting": __TablesBase["weddingAgentSetting"];
  /** @deprecated Use `weddingMessage` instead. This alias will be removed in the next major version. */
  readonly "wedding_message": __TablesBase["weddingMessage"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

