// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  weddingId: __t.u64().name("wedding_id"),
  kind: __t.string(),
  status: __t.string(),
  itemCount: __t.u32().name("item_count"),
  submittedBy: __t.identity().name("submitted_by"),
  createdAt: __t.timestamp().name("created_at"),
});
