// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  menuId: __t.u64().name("menu_id"),
  course: __t.string(),
  dish: __t.string(),
  dietaryTags: __t.option(__t.string()).name("dietary_tags"),
  state: __t.string(),
  source: __t.string(),
  updatedBy: __t.identity().name("updated_by"),
  confidence: __t.f32(),
  updatedAt: __t.timestamp().name("updated_at"),
});
