// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  weddingId: __t.u64().name("wedding_id"),
  eventId: __t.u64().name("event_id"),
  title: __t.string(),
  serviceStyle: __t.string().name("service_style"),
  guestCount: __t.option(__t.u32()).name("guest_count"),
  dietaryNotes: __t.option(__t.string()).name("dietary_notes"),
  state: __t.string(),
  source: __t.string(),
  updatedBy: __t.identity().name("updated_by"),
  confidence: __t.f32(),
  updatedAt: __t.timestamp().name("updated_at"),
  finalizedBy: __t.option(__t.identity()).name("finalized_by"),
  finalizedAt: __t.option(__t.timestamp()).name("finalized_at"),
});
