// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  connected: __t.bool(),
  role: __t.string(),
  side: __t.option(__t.string()),
  phone: __t.option(__t.string()),
  dateOfBirth: __t.option(__t.string()).name("date_of_birth"),
  gender: __t.option(__t.string()),
  mealPreference: __t.option(__t.string()).name("meal_preference"),
  profileState: __t.string().name("profile_state"),
  profileSource: __t.string().name("profile_source"),
  profileUpdatedAt: __t.option(__t.timestamp()).name("profile_updated_at"),
  preferredLanguage: __t.string().name("preferred_language"),
});
