// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  title: __t.string(),
  ownerIdentity: __t.identity().name("owner_identity"),
  done: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  dueAt: __t.option(__t.timestamp()).name("due_at"),
  state: __t.string(),
  source: __t.string(),
  reportedBy: __t.option(__t.identity()).name("reported_by"),
  confidence: __t.option(__t.f32()),
  reportedAt: __t.option(__t.timestamp()).name("reported_at"),
  weddingId: __t.option(__t.u64()).name("wedding_id"),
});
