// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Decision = __t.object("Decision", {
  id: __t.u64(),
  title: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  deciderIdentity: __t.option(__t.identity()),
  lockedOptionId: __t.option(__t.u64()),
  weddingId: __t.option(__t.u64()),
});
export type Decision = __Infer<typeof Decision>;

export const DecisionOption = __t.object("DecisionOption", {
  id: __t.u64(),
  decisionId: __t.u64(),
  label: __t.string(),
});
export type DecisionOption = __Infer<typeof DecisionOption>;

export const Event = __t.object("Event", {
  id: __t.u64(),
  weddingId: __t.u64(),
  title: __t.string(),
  startsAt: __t.option(__t.timestamp()),
  venue: __t.option(__t.string()),
  state: __t.string(),
  source: __t.string(),
  updatedBy: __t.identity(),
  confidence: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Event = __Infer<typeof Event>;

export const Expense = __t.object("Expense", {
  id: __t.u64(),
  weddingId: __t.u64(),
  category: __t.string(),
  label: __t.string(),
  amountPaise: __t.i64(),
  paid: __t.bool(),
  state: __t.string(),
  source: __t.string(),
  updatedBy: __t.identity(),
  confidence: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Expense = __Infer<typeof Expense>;

export const IngestSource = __t.object("IngestSource", {
  id: __t.u64(),
  weddingId: __t.u64(),
  kind: __t.string(),
  status: __t.string(),
  itemCount: __t.u32(),
  submittedBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type IngestSource = __Infer<typeof IngestSource>;

export const Member = __t.object("Member", {
  id: __t.u64(),
  weddingId: __t.u64(),
  identity: __t.identity(),
  role: __t.string(),
  side: __t.option(__t.string()),
  joinedAt: __t.timestamp(),
  state: __t.string(),
  source: __t.string(),
  updatedBy: __t.identity(),
  confidence: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Member = __Infer<typeof Member>;

export const Participant = __t.object("Participant", {
  identity: __t.identity(),
  name: __t.string(),
  connected: __t.bool(),
  role: __t.string(),
  side: __t.option(__t.string()),
  phone: __t.option(__t.string()),
  dateOfBirth: __t.option(__t.string()),
  gender: __t.option(__t.string()),
  mealPreference: __t.option(__t.string()),
  profileState: __t.string(),
  profileSource: __t.string(),
  profileUpdatedAt: __t.option(__t.timestamp()),
});
export type Participant = __Infer<typeof Participant>;

export const Task = __t.object("Task", {
  id: __t.u64(),
  title: __t.string(),
  ownerIdentity: __t.identity(),
  done: __t.bool(),
  createdAt: __t.timestamp(),
  dueAt: __t.option(__t.timestamp()),
  state: __t.string(),
  source: __t.string(),
  reportedBy: __t.option(__t.identity()),
  confidence: __t.option(__t.f32()),
  reportedAt: __t.option(__t.timestamp()),
  weddingId: __t.option(__t.u64()),
});
export type Task = __Infer<typeof Task>;

export const Vote = __t.object("Vote", {
  id: __t.u64(),
  decisionId: __t.u64(),
  optionId: __t.u64(),
  voterIdentity: __t.identity(),
  votedAt: __t.timestamp(),
});
export type Vote = __Infer<typeof Vote>;

export const WebhookSecret = __t.object("WebhookSecret", {
  id: __t.u8(),
  value: __t.string(),
});
export type WebhookSecret = __Infer<typeof WebhookSecret>;

export const Wedding = __t.object("Wedding", {
  id: __t.u64(),
  createdBy: __t.identity(),
  brideName: __t.string(),
  groomName: __t.string(),
  city: __t.string(),
  dateLabel: __t.string(),
  state: __t.string(),
  source: __t.string(),
  updatedBy: __t.identity(),
  confidence: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Wedding = __Infer<typeof Wedding>;

export const WeddingInvitation = __t.object("WeddingInvitation", {
  id: __t.u64(),
  weddingId: __t.u64(),
  code: __t.string(),
  role: __t.string(),
  side: __t.option(__t.string()),
  status: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  acceptedBy: __t.option(__t.identity()),
  acceptedAt: __t.option(__t.timestamp()),
});
export type WeddingInvitation = __Infer<typeof WeddingInvitation>;

