// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Decision = __t.object("Decision", {
  id: __t.u64(),
  title: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  deciderIdentity: __t.option(__t.identity()),
  lockedOptionId: __t.option(__t.u64()),
});
export type Decision = __Infer<typeof Decision>;

export const DecisionOption = __t.object("DecisionOption", {
  id: __t.u64(),
  decisionId: __t.u64(),
  label: __t.string(),
});
export type DecisionOption = __Infer<typeof DecisionOption>;

export const Participant = __t.object("Participant", {
  identity: __t.identity(),
  name: __t.string(),
  connected: __t.bool(),
  role: __t.string(),
  side: __t.option(__t.string()),
  phone: __t.option(__t.string()),
});
export type Participant = __Infer<typeof Participant>;

export const Task = __t.object("Task", {
  id: __t.u64(),
  title: __t.string(),
  ownerIdentity: __t.identity(),
  done: __t.bool(),
  createdAt: __t.timestamp(),
  dueAt: __t.option(__t.timestamp()),
  state: __t.string(),
  source: __t.string(),
  reportedBy: __t.option(__t.identity()),
  confidence: __t.option(__t.f32()),
  reportedAt: __t.option(__t.timestamp()),
});
export type Task = __Infer<typeof Task>;

export const Vote = __t.object("Vote", {
  id: __t.u64(),
  decisionId: __t.u64(),
  optionId: __t.u64(),
  voterIdentity: __t.identity(),
  votedAt: __t.timestamp(),
});
export type Vote = __Infer<typeof Vote>;

export const WebhookSecret = __t.object("WebhookSecret", {
  id: __t.u8(),
  value: __t.string(),
});
export type WebhookSecret = __Infer<typeof WebhookSecret>;

