// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  createdBy: __t.identity().name("created_by"),
  primaryName: __t.string().name("primary_name"),
  partnerName: __t.string().name("partner_name"),
  city: __t.string(),
  dateLabel: __t.string().name("date_label"),
  state: __t.string(),
  source: __t.string(),
  updatedBy: __t.identity().name("updated_by"),
  confidence: __t.f32(),
  updatedAt: __t.timestamp().name("updated_at"),
});
