// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptWeddingInvitationReducer from "../accept_wedding_invitation_reducer";
import AddEventChecklistItemReducer from "../add_event_checklist_item_reducer";
import AddMemberReducer from "../add_member_reducer";
import ApplyEventTemplateReducer from "../apply_event_template_reducer";
import CastVoteReducer from "../cast_vote_reducer";
import ConfirmEventChecklistItemReducer from "../confirm_event_checklist_item_reducer";
import ConfirmExpenseReducer from "../confirm_expense_reducer";
import ConfirmReportedTaskReducer from "../confirm_reported_task_reducer";
import CreateCustomWeddingAgentReducer from "../create_custom_wedding_agent_reducer";
import CreateDecisionReducer from "../create_decision_reducer";
import CreateEventReducer from "../create_event_reducer";
import CreateExpenseReducer from "../create_expense_reducer";
import CreateTaskReducer from "../create_task_reducer";
import CreateVendorReducer from "../create_vendor_reducer";
import CreateWeddingReducer from "../create_wedding_reducer";
import CreateWeddingInvitationReducer from "../create_wedding_invitation_reducer";
import DeclineWeddingInvitationReducer from "../decline_wedding_invitation_reducer";
import DeleteEventReducer from "../delete_event_reducer";
import LinkPhoneReducer from "../link_phone_reducer";
import LockDecisionReducer from "../lock_decision_reducer";
import RecordImportedExpenseReducer from "../record_imported_expense_reducer";
import RequestCoordinatorActionReducer from "../request_coordinator_action_reducer";
import RequestIngestReducer from "../request_ingest_reducer";
import SeedPriyaRahulDemoReducer from "../seed_priya_rahul_demo_reducer";
import SendWeddingMessageReducer from "../send_wedding_message_reducer";
import SetBudgetReducer from "../set_budget_reducer";
import SetDeciderReducer from "../set_decider_reducer";
import SetEventChecklistItemDoneReducer from "../set_event_checklist_item_done_reducer";
import SetMembershipRoleReducer from "../set_membership_role_reducer";
import SetMembershipSideReducer from "../set_membership_side_reducer";
import SetNameReducer from "../set_name_reducer";
import SetRoleReducer from "../set_role_reducer";
import SetSideReducer from "../set_side_reducer";
import SetVendorBookingStateReducer from "../set_vendor_booking_state_reducer";
import SetVendorConsentReducer from "../set_vendor_consent_reducer";
import SetWebhookSecretReducer from "../set_webhook_secret_reducer";
import SetWeddingAgentReducer from "../set_wedding_agent_reducer";
import SetWeddingAgentInstructionsReducer from "../set_wedding_agent_instructions_reducer";
import ToggleTaskReducer from "../toggle_task_reducer";
import UpdateEventReducer from "../update_event_reducer";
import UpdateMyProfileReducer from "../update_my_profile_reducer";

export type AcceptWeddingInvitationParams = __Infer<typeof AcceptWeddingInvitationReducer>;
export type AddEventChecklistItemParams = __Infer<typeof AddEventChecklistItemReducer>;
export type AddMemberParams = __Infer<typeof AddMemberReducer>;
export type ApplyEventTemplateParams = __Infer<typeof ApplyEventTemplateReducer>;
export type CastVoteParams = __Infer<typeof CastVoteReducer>;
export type ConfirmEventChecklistItemParams = __Infer<typeof ConfirmEventChecklistItemReducer>;
export type ConfirmExpenseParams = __Infer<typeof ConfirmExpenseReducer>;
export type ConfirmReportedTaskParams = __Infer<typeof ConfirmReportedTaskReducer>;
export type CreateCustomWeddingAgentParams = __Infer<typeof CreateCustomWeddingAgentReducer>;
export type CreateDecisionParams = __Infer<typeof CreateDecisionReducer>;
export type CreateEventParams = __Infer<typeof CreateEventReducer>;
export type CreateExpenseParams = __Infer<typeof CreateExpenseReducer>;
export type CreateTaskParams = __Infer<typeof CreateTaskReducer>;
export type CreateVendorParams = __Infer<typeof CreateVendorReducer>;
export type CreateWeddingParams = __Infer<typeof CreateWeddingReducer>;
export type CreateWeddingInvitationParams = __Infer<typeof CreateWeddingInvitationReducer>;
export type DeclineWeddingInvitationParams = __Infer<typeof DeclineWeddingInvitationReducer>;
export type DeleteEventParams = __Infer<typeof DeleteEventReducer>;
export type LinkPhoneParams = __Infer<typeof LinkPhoneReducer>;
export type LockDecisionParams = __Infer<typeof LockDecisionReducer>;
export type RecordImportedExpenseParams = __Infer<typeof RecordImportedExpenseReducer>;
export type RequestCoordinatorActionParams = __Infer<typeof RequestCoordinatorActionReducer>;
export type RequestIngestParams = __Infer<typeof RequestIngestReducer>;
export type SeedPriyaRahulDemoParams = __Infer<typeof SeedPriyaRahulDemoReducer>;
export type SendWeddingMessageParams = __Infer<typeof SendWeddingMessageReducer>;
export type SetBudgetParams = __Infer<typeof SetBudgetReducer>;
export type SetDeciderParams = __Infer<typeof SetDeciderReducer>;
export type SetEventChecklistItemDoneParams = __Infer<typeof SetEventChecklistItemDoneReducer>;
export type SetMembershipRoleParams = __Infer<typeof SetMembershipRoleReducer>;
export type SetMembershipSideParams = __Infer<typeof SetMembershipSideReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetRoleParams = __Infer<typeof SetRoleReducer>;
export type SetSideParams = __Infer<typeof SetSideReducer>;
export type SetVendorBookingStateParams = __Infer<typeof SetVendorBookingStateReducer>;
export type SetVendorConsentParams = __Infer<typeof SetVendorConsentReducer>;
export type SetWebhookSecretParams = __Infer<typeof SetWebhookSecretReducer>;
export type SetWeddingAgentParams = __Infer<typeof SetWeddingAgentReducer>;
export type SetWeddingAgentInstructionsParams = __Infer<typeof SetWeddingAgentInstructionsReducer>;
export type ToggleTaskParams = __Infer<typeof ToggleTaskReducer>;
export type UpdateEventParams = __Infer<typeof UpdateEventReducer>;
export type UpdateMyProfileParams = __Infer<typeof UpdateMyProfileReducer>;

